Fix Issue #62: Convert html-code to plain text
PNUdev/radio-service pull request #63
Opened 2020-12-25 12:41 UTC by pikulo-kama

I'm not sure whether data renders in right format.

2020-12-25 12:47 UTC, Igor-Polatajko requested changes
Could you, please, fix it for the place in video displaying component, where the title of the video is displayed?

2020-12-25 18:29 UTC, pikulo-kama commented
Issue resolved
![Fix #62](https://user-images.githubusercontent.com/72470924/103140488-aa1baa80-46ef-11eb-9a92-ad01c78609aa.png)

2020-12-25 19:20 UTC, Igor-Polatajko commented on radio-service-ui/src/utils/char_escaper.js
> +  return htmlToText(data);
I believe, we should also strip html tags here.

```
import stripHtml from "string-strip-html";

stripHtml(data).result
```

2020-12-26 17:21 UTC, Igor-Polatajko approved these changes

2020-12-26 17:30 UTC, merged